export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_USER_FROM_TOKEN = 'SET_USER_FROM_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_ACCESSTOKEN = 'UPDATE_ACCESSTOKEN';
